'use client'

import { motion } from 'framer-motion'
import { Flame, Heart, ChefHat, Sparkles, Star } from 'lucide-react'
import GlassCard from '@/components/ui/GlassCard'
import Link from 'next/link'
import Button from '@/components/ui/Button'

const features = [
  { icon: '🍳', title: 'Real Recipes',   desc: 'Every recipe is tested and crafted with care, not generated by AI.' },
  { icon: '📱', title: 'Clean & Fast',   desc: 'No life stories, no ads — just the recipe you came for.' },
  { icon: '🌿', title: 'All Categories', desc: 'From quick weekday meals to indulgent weekend feasts.' },
]

export default function AboutPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 space-y-12 pt-8">

      {/* Hero */}
      <motion.div
        initial={{ opacity: 0, y: 28 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
        className="text-center space-y-5"
      >
        {/* Logo icon */}
        <div className="relative mx-auto w-20 h-20">
          <span className="absolute inset-0 rounded-3xl bg-brand-500/20 animate-breathe" />
          <span className="relative flex h-20 w-20 items-center justify-center rounded-3xl bg-gradient-to-br from-brand-400 to-brand-600 shadow-glow">
            <Flame className="h-10 w-10 text-white" />
          </span>
        </div>

        <h1 className="font-display text-4xl sm:text-5xl font-bold text-white">
          ALONE{' '}
          <span className="text-gradient-brand">recipes</span>
        </h1>
        <p className="text-white/40 font-body leading-relaxed text-lg">
          A personal cookbook — crafted in solitude, shared with the world.
        </p>
      </motion.div>

      {/* Story card */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.12 }}
      >
        <GlassCard className="p-8 space-y-5">
          <div className="flex items-center gap-3">
            <div className="h-8 w-8 rounded-lg bg-brand-500/15 border border-brand-400/20 flex items-center justify-center">
              <Heart className="h-4 w-4 text-brand-400" />
            </div>
            <h2 className="font-display text-xl font-bold text-white">The Story</h2>
          </div>
          <p className="text-white/50 font-body leading-relaxed">
            Every great dish starts with a single moment of inspiration — usually alone in
            the kitchen, late at night, experimenting with whatever's in the fridge.
            This is a collection of those moments, curated and shared for anyone who loves
            to cook, discover, and savour.
          </p>
          <p className="text-white/50 font-body leading-relaxed">
            No bloated life stories before the recipe. Just beautiful food, clean
            instructions, and the joy of cooking.
          </p>

          {/* Divider */}
          <div className="h-px bg-gradient-to-r from-transparent via-white/[0.08] to-transparent" />

          {/* Feature grid */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-1">
            {features.map(({ icon, title, desc }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.25 + i * 0.08, duration: 0.4 }}
                className="flex flex-col gap-2 p-3 rounded-xl bg-white/[0.03] border border-white/[0.06]"
              >
                <span className="text-xl">{icon}</span>
                <p className="font-body text-sm font-semibold text-white/70">{title}</p>
                <p className="font-body text-xs text-white/30 leading-relaxed">{desc}</p>
              </motion.div>
            ))}
          </div>
        </GlassCard>
      </motion.div>

      {/* CTA */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.28 }}
        className="flex flex-col sm:flex-row gap-3 justify-center"
      >
        <Link href="/">
          <Button variant="primary" size="lg">
            <ChefHat className="h-4 w-4" /> Browse Recipes
          </Button>
        </Link>
        <Link href="/admin/login">
          <Button variant="glass" size="lg">
            Admin Panel
          </Button>
        </Link>
      </motion.div>
    </div>
  )
}
